-- Plan entitlements: feature flags per plan.
-- Run in Supabase SQL Editor.

create table if not exists public.plan_entitlements (
  plan_id text not null,
  feature_key text not null,
  enabled boolean not null default true,
  value text,
  metadata jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (plan_id, feature_key)
);

-- Seed entitlements matching the credit economy spec.
insert into public.plan_entitlements (plan_id, feature_key, enabled, value) values
  -- free_trial
  ('free_trial', 'interface_lite', true, 'lite'),
  ('free_trial', 'interface_pro', false, 'pro'),
  ('free_trial', 'audio_basic', true, 'basic'),
  ('free_trial', 'export_mp3', true, 'mp3'),
  ('free_trial', 'library_limited', true, 'limited'),
  ('free_trial', 'support_community', true, 'community'),
  -- standard_monthly / standard_annual
  ('standard_monthly', 'interface_lite', true, 'lite'),
  ('standard_monthly', 'interface_pro', false, 'pro'),
  ('standard_monthly', 'audio_advanced', true, 'advanced'),
  ('standard_monthly', 'export_wav', true, 'wav'),
  ('standard_monthly', 'library_10gb', true, '10gb'),
  ('standard_monthly', 'support_email', true, 'email'),
  ('standard_annual', 'interface_lite', true, 'lite'),
  ('standard_annual', 'interface_pro', false, 'pro'),
  ('standard_annual', 'audio_advanced', true, 'advanced'),
  ('standard_annual', 'export_wav', true, 'wav'),
  ('standard_annual', 'library_10gb', true, '10gb'),
  ('standard_annual', 'support_email', true, 'email'),
  -- premium_flex_*
  ('premium_flex_50', 'interface_lite', true, 'lite'),
  ('premium_flex_50', 'interface_pro', true, 'pro'),
  ('premium_flex_50', 'audio_advanced_plugins', true, 'advanced+plugins'),
  ('premium_flex_50', 'export_wav', true, 'wav'),
  ('premium_flex_50', 'export_midi', true, 'midi'),
  ('premium_flex_50', 'export_mp3', true, 'mp3'),
  ('premium_flex_50', 'library_full', true, 'full'),
  ('premium_flex_50', 'support_priority', true, 'priority'),
  ('premium_flex_100', 'interface_lite', true, 'lite'),
  ('premium_flex_100', 'interface_pro', true, 'pro'),
  ('premium_flex_100', 'audio_advanced_plugins', true, 'advanced+plugins'),
  ('premium_flex_100', 'export_wav', true, 'wav'),
  ('premium_flex_100', 'export_midi', true, 'midi'),
  ('premium_flex_100', 'export_mp3', true, 'mp3'),
  ('premium_flex_100', 'library_full', true, 'full'),
  ('premium_flex_100', 'support_priority', true, 'priority'),
  ('premium_flex_500', 'interface_lite', true, 'lite'),
  ('premium_flex_500', 'interface_pro', true, 'pro'),
  ('premium_flex_500', 'audio_advanced_plugins', true, 'advanced+plugins'),
  ('premium_flex_500', 'export_wav', true, 'wav'),
  ('premium_flex_500', 'export_midi', true, 'midi'),
  ('premium_flex_500', 'export_mp3', true, 'mp3'),
  ('premium_flex_500', 'library_full', true, 'full'),
  ('premium_flex_500', 'support_priority', true, 'priority'),
  ('premium_flex_1000', 'interface_lite', true, 'lite'),
  ('premium_flex_1000', 'interface_pro', true, 'pro'),
  ('premium_flex_1000', 'audio_advanced_plugins', true, 'advanced+plugins'),
  ('premium_flex_1000', 'export_wav', true, 'wav'),
  ('premium_flex_1000', 'export_midi', true, 'midi'),
  ('premium_flex_1000', 'export_mp3', true, 'mp3'),
  ('premium_flex_1000', 'library_full', true, 'full'),
  ('premium_flex_1000', 'support_priority', true, 'priority'),
  ('premium_flex_3000', 'interface_lite', true, 'lite'),
  ('premium_flex_3000', 'interface_pro', true, 'pro'),
  ('premium_flex_3000', 'audio_advanced_plugins', true, 'advanced+plugins'),
  ('premium_flex_3000', 'export_wav', true, 'wav'),
  ('premium_flex_3000', 'export_midi', true, 'midi'),
  ('premium_flex_3000', 'export_mp3', true, 'mp3'),
  ('premium_flex_3000', 'library_full', true, 'full'),
  ('premium_flex_3000', 'support_priority', true, 'priority'),
  -- enterprise_custom
  ('enterprise_custom', 'interface_lite', true, 'lite'),
  ('enterprise_custom', 'interface_pro', true, 'pro'),
  ('enterprise_custom', 'audio_enterprise', true, 'enterprise'),
  ('enterprise_custom', 'export_all', true, 'all'),
  ('enterprise_custom', 'library_enterprise', true, 'enterprise'),
  ('enterprise_custom', 'support_247', true, '247')
on conflict (plan_id, feature_key) do nothing;