// Extracts the engine RPC definitions from supabase/schema/user_credits.sql
// into the standalone prod follow-up credit_engine_legacy_compat.sql.
// (Main migration already applied; prod must NOT re-run it.)
// Run: node scripts/build_legacy_compat.mjs
import * as fs from "fs";
import * as path from "path";

const schemaDir = path.join(process.cwd(), "supabase", "schema");
const src = fs.readFileSync(path.join(schemaDir, "user_credits.sql"), "utf-8");

const startMarker = "-- 3. reserve_credits";
const endMarker = "grant execute on function private.refill_credits(uuid, integer, text) to service_role;";
const start = src.indexOf(startMarker);
const end = src.indexOf(endMarker);
if (start < 0 || end < 0) throw new Error("markers not found");
const body = src.slice(start, end + endMarker.length);

const out = `-- Credit Engine LEGACY-COMPAT follow-up (standalone, additive).
-- Generated by scripts/build_legacy_compat.mjs from user_credits.sql.
-- Do NOT hand-edit: change user_credits.sql and rebuild.
-- WHY: production legacy columns user_credits.id / trial_activated and
-- credit_transactions.transaction_type / description are NOT NULL, so engine
-- RPC inserts must write them. Engine columns stay authoritative; legacy
-- values are best-effort maps of observed legacy vocab ('earned'/'spent').
-- Run AFTER credit_engine_public_wrappers.sql. Idempotent (OR REPLACE).

${body}
`;

const outFile = path.join(schemaDir, "credit_engine_legacy_compat.sql");
fs.writeFileSync(outFile, out);
console.log(`Wrote ${outFile} (${out.length} chars)`);
